export const HOME_PATH = '/';
// export const SUBSCRIPTIONS_PATH = '/subscriptions';
export const STORAGE_PATH = '/storage';
export const PAYMENT_OPTIONS_PATH = '/payment';
export const PAYMENT_CONFIRM_PATH = '/payment/confirm';
export const PASSWORD_SETTINGS_PATH = '/password';
export const AVATAR_SETTINGS_PATH = '/avatar';
export const PUBLIC_PROFILE_PATH = '/public-profile';
export const MANAGE_ACCOUNT_PATH = '/manage';
